### PR TITLE
Add figwheel and basic ClojureScript infrastructure

### PR DESCRIPTION
**Pull request by lvh**
This should solve #64 enough so that @smogg can get started.

### CODE REVIEW

**Comment by smogg** [comment]
LGTM

**Comment by sirsean** [comment]
Could we add a little text to the README indicating how to run the UI? Maybe it's as easy as `lein figwheel` but as someone who's new to this I'd feel more comfortable if that were spelled out. ;-)

**Comment by lvh** [comment]
@smogg Did you close+reopen this to start the builds again? Because that's what just happened ;)

**Comment by lvh** [comment]
@sirsean I'm not sure how to document this right now. For one, `docker compose up` doesn't get you the UI, and the testing environment doesn't test inside docker at all. This is mostly just so @smogg can start doing something, but we haven't really figured out how we're going to serve the UI yet at all. (I think it should be part of `docker compose up`.)

**Comment by smogg** [comment]
@lvh Let's pretend I did. 

<sup>(It was a missclick)</sup>

**Comment by lvh** [comment]
I've started writing the wiki page as promised: https://github.com/RackSec/desdemona/wiki/Development

**Comment by lvh** [comment]
@sirsean If this PR looks good to you and so does the wiki documentation, could you please merge this?

**Comment by sirsean** [comment]
Yup. :+1:

**Pull request merged**
