### PR TITLE
Specify line length in editorconfig

### PR DESCRIPTION
**Pull request by lvh**

### CODE REVIEW

**Comment by ehashman** [comment]
This LGTM, but the build failed because the badges on the README (lines 3-4) are too long. Is there any way to ignore that? I can merge this but the build is going to break from now on as a result.

**Comment by lvh** [comment]
Looks like the only granularity you can get there is file-level. Since part of this touched the README, I'm disinclined to do that. However, I used markdown ref syntax instead to just make the line shorter :) (Also I think that most Markdown parsers may even accept newlines inside matched delimiters)

**Comment by ehashman** [comment]
The badges are rendering weird for me: https://github.com/lvh/desdemona/blob/b9e7e7c2b2767a7634a74edf790ae8ccf91a6972/README.md

**Comment by sirsean** [comment]
👍

**Pull request merged**
