### PR TITLE
remove travis yml since we're moving to jenkins

### PR DESCRIPTION
**Pull request by reaperhulk**
This shouldn't be merged yet because travis is still turned on for the repo so it will attempt to guess what to do and fail.

### CODE REVIEW

**Comment by reaperhulk** [comment]
(I am hoping the codecov endless delay here is because travis reported once to this PR and so codecov is confused)

**Comment by lvh** [comment]
Shouldn't Travis just be configured not to run in the absence of a .travis.yml? It appears that may already be the case.

**Comment by reaperhulk** [comment]
It was not configured that way, but it is now :)

**Comment by reaperhulk** [comment]
Going to close this and open a new mostly identical PR to see if codecov is smarter.

**Pull request closed without merging**
