### PR TITLE
Add ClojureScript testing infrastructure based on doo + karma

### PR DESCRIPTION
**Pull request by lvh**
This builds on #68. This is currently a WIP; it is only open so that Travis builds stuff for me on occasion.

### CODE REVIEW

**Comment by lvh** [comment]
I have confirmed in https://travis-ci.org/RackSec/desdemona/jobs/114371032 that a failed doo test will fail the CI.

**Comment by lvh** [comment]
Could someone please review this? I'm pretty sure it's ready to merge.

**Comment by sirsean** [comment]
Does this need master merged into it? There are some "changed" the diff is showing that I think are already in master.

**Comment by lvh** [comment]
Merged forward; diff looks better now :)

**Comment by sirsean** [comment]
Sure does. :+1:

(I have no experience with ClojureScript or doo, etc, but assuming those are things that work, and CI appears to confirm that, then this looks good to me.)

**Pull request merged**
