### PR TITLE
Delaying the start of Kafka and Desdemona

### PR DESCRIPTION
**Pull request by sirsean**
This gives everything time to finish starting up.

Kafka waits for 10 seconds for Zookeeper to finish. Desdemona itself waits 20 seconds for Kafka. (The waiting starts at the same time, so Desdemona's wait has to include Kafka's.)

### CODE REVIEW

**Comment by lvh** [comment]
Does this reference #45, close it, or what? I know this is a less-than-perfect stopgap; and at some point we probably want retry logic instead. Is that captured in the issue tracker somewhere?

**Comment by lvh** [comment]
Other than that, this patch seems great. Perhaps it would be useful to add references to the issue tracker, though? (That's a nit; up to you if it ought to be resolved.)

**Comment by sirsean** [comment]
This doesn't really do anything until we figure out why the Docker build still doesn't pass in CI:

```E: Failed to fetch http://httpredir.debian.org/debian/pool/main/l/llvm-toolchain-3.5/libllvm3.5_3.5-10_amd64.deb  Error reading from server. Remote end closed connection [IP: 128.31.0.66 80]```

It _looks_ like a network issue?

**Comment by lvh** [comment]
It appears that the build failed:

https://travis-ci.org/RackSec/desdemona/jobs/116238227

... but only because the network connection blew up..

**Comment by lvh** [comment]
You're faster than me :D I was just about to do the same thing.

**Comment by sirsean** [comment]
My inclination is that once this reliably passes in CI, it closes #45 and we should make a new issue for the backoff retry logic. Which is important but less essential than "we can literally start the server".

**Comment by lvh** [comment]
:+1:

**Comment by lvh** [comment]
IT WORKED! 

Is it bad if I feel this should also make docker gating? I could see if you want that to be a different PR, though :)

**Comment by sirsean** [comment]
I don't think it's bad. Being able to make the Docker build gating is the ideal result of this.

**Comment by ehashman** [comment]
SOOO happy to see the docker build work!!! :tada:

**Comment by lvh** [comment]
(To be honest I kinda want to make everything gating now but the rest is definitely a separate PR :))

**Comment by lvh** [comment]
Looks good to me; feel free to merge whenever CI passes, which hopefully will be some time today.

**Comment by ehashman** [comment]
+1 commit name and very +1 to this PR. Merging.

**Pull request merged**
