### PR TITLE
Backport config.edn

### PR DESCRIPTION
**Pull request by sirsean**
This was mostly done in #21 but there's a little bit of cleanup/improvement here:

* Removed old config files that are no longer used, only using new config.edn. 
* Added some scripts to help you connect to your local Kafka/MySQL Docker containers and to submit the job.

### CODE REVIEW

**Comment by lvh** [comment]
The scripts' contents are referred to in the README; you should probably update the README to use the scripts instead.

**Comment by lvh** [comment]
(This looks good to me other than that comment.)

**Comment by sirsean** [comment]
Good point about the README. :+1:

**Comment by lvh** [comment]
I'll merge pretty much anything with a negative diff ;)

**Pull request merged**
