### PR TITLE
Add docker-compose to Travis

### LINKED ISSUE #60: docker-compose isn't avialable in current container-based infra
See: https://travis-ci.org/RackSec/desdemona/jobs/113481387#L279

Thanks to @ehashman for finding this.

### PR DESCRIPTION
**Pull request by lvh**
Closes #60.

### CODE REVIEW

**Comment by lvh** [comment]
```
/usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
```

I'm pretty happy that we get an exception about that now :D

**Comment by lvh** [comment]
I typed the letters `PYTHONWARNINGS=ignore` into a commit so I'd like @reaperhulk to sign off :)

**Comment by lvh** [comment]
Except of course docker the service is unavailable on the old container infra, so now I'm at:

```
$ sudo service docker start

docker: unrecognized service
```

**Comment by lvh** [comment]
Unfortunately, it looks like Travis still doesn't support docker-in-docker on the container infra, and so we have to move back to GCE infrastructure (and slow builds) for the time being. cc @reaperhulk to sign off on this actually being true.

**Comment by lvh** [comment]
cc @sirsean -- that's not to say that your opinion isn't appreciated here; I'm just pinging @reaperhulk because he's had some experience with Travis CI :)

**Comment by sirsean** [comment]
Haha I'd defer to @reaperhulk on that too. He has way more insight into Travis CI than I do.

**Comment by reaperhulk** [comment]
That is correct. Docker-in-docker is not a thing the container infra supports at this time (although docker itself is entirely capable of it).

**Comment by lvh** [comment]
OK, since this appears to be the only way to get a working docker + working builds, it seems like this ought to be merged.

**Comment by ehashman** [comment]
Cool, LGTM.

Do you want to keep all that history for this two-line change or is it okay to squash those commits before I merge?

**Comment by lvh** [comment]
I think the struggle can be instructive, yes :) Thanks for the review!

**Pull request merged**
